version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresssql/data
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
# volumes:
#   pgdata:
#   mogodata:
  




