version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresssql/data
volumes:
  pgdata:

